do more error checking

diff --git a/lib/formatusb_lib b/lib/formatusb_lib
--- a/lib/formatusb_lib
+++ b/lib/formatusb_lib
@@ -11,8 +11,10 @@ format="$2"
 label="$3"
 part="$4"
 
+LOG="/tmp/formatter.log"
+
 echo device is $device format is $format 
-echo label is $label
+echo label is $label 
 
 clearpartions(){
 	live-usb-maker gui partition-clear --color=off -t "$device"
@@ -20,8 +22,9 @@ clearpartions(){
 
 unmount_partitions()
 {
-	local umount_device=$device*
+	local umount_device=$device* 
 	umount /dev/$umount_device 2>/dev/null
+	checkerrorcode "unmount partitions"
 }
 
 ##clear_partitions from live-usb-maker by James Bowlin (BitJam) for antiX
@@ -39,12 +42,14 @@ clear_partitions()
     #echo -e "Total bytes: $bytes\nTotal blocks: $total_blocks" 
 
     # Clear out previous primary partition table
-    dd if=/dev/zero of=$dev bs=$block_size count=$pt_cnt
+    dd if=/dev/zero of=$dev bs=$block_size count=$pt_cnt 
+    checkerrorcode "primary partition table clear"
     
     sleep 1
 
     # Clear out sneaky iso-hybrid partition table
-    dd if=/dev/zero of=$dev bs=$block_size count=$pt_cnt seek=64
+    dd if=/dev/zero of=$dev bs=$block_size count=$pt_cnt seek=64 
+    checkerrorcode "iso-hybrid partition table clear"
 
 	sleep 1
 	
@@ -52,11 +57,15 @@ clear_partitions()
     local offset=$((total_blocks - $pt_cnt))
 
     # Clear out secondary gpt partition table
-    dd conv=notrunc if=/dev/zero of=$dev bs=$block_size count=$pt_cnt seek=$offset
+    dd conv=notrunc if=/dev/zero of=$dev bs=$block_size count=$pt_cnt seek=$offset 
+    
+    checkerrorcode "secondary partition table clear"
+    
     sleep 1
     # Tell kernel the partition table has changed
-    echo "refresh partitions info $dev"
-    /sbin/partprobe -s $dev
+    echo "refresh partitions info $dev" 
+    /sbin/partprobe -s $dev 
+    checkerrorcode "refresh partitions info"
     sleep 1
 }
 
@@ -65,12 +74,16 @@ create_partition()
 	local dev=/dev/$device
 	unmount_partitions
 	sleep 1
-	parted -s $dev mklabel msdos
+	parted -s $dev mklabel msdos 
+	checkerrorcode "making new partition table"
 	sleep 1
-	/sbin/partprobe $dev
-	parted -s -a optimal $dev mkpart primary 1 100%
+	/sbin/partprobe $dev 
+	checkerrorcode "refresh partitions info"
+	parted -s -a optimal $dev mkpart primary 1 100% 
+	checkerrorcode "create new partition"
 	sleep 1
-	/sbin/partprobe $dev
+	/sbin/partprobe $dev 
+	checkerrorcode "refresh partitions info"
 	sleep 1
 }
 
@@ -83,22 +96,26 @@ labelusb(){
 
 #ensure device is unmounted
 umount -q /dev/"$device$partnum" 2>/dev/null
+checkerrorcode "unmount partitions"
 
     
 case $format in 
 
-	vfat) fatlabel /dev/"$device$partnum" "$label" ;;
+	vfat) fatlabel /dev/"$device$partnum" "$label"  ;;
 	
-	ext4)  e2label /dev/"$device$partnum" "$label" ;;
+	ext4)  e2label /dev/"$device$partnum" "$label"  ;;
 	
-	ntfs)  ntfslabel /dev/"$device$partnum" "$label" ;;
+	ntfs)  ntfslabel /dev/"$device$partnum" "$label"  ;;
 	
-	exfat) exfatlabel /dev/"$device$partnum" "$label" ;;
+	exfat) exfatlabel /dev/"$device$partnum" "$label"  ;;
 	
-	*)	echo "unknown format, exiting" ;;
+	*)	echo "unknown format, exiting"  ;;
 
 esac
+
+checkerrorcode "label partition"
 }
+
 partitionrefresh(){
 	
 	##need device not partition
@@ -119,9 +136,10 @@ partitionrefresh(){
 		refreshdevice=${device//[0-9]/}
 	fi
 
-echo "Refresh Partitions $refreshdevice"
+echo "Refresh Partitions $refreshdevice"  
 
-/sbin/partprobe "/dev/$refreshdevice"
+/sbin/partprobe "/dev/$refreshdevice"  
+checkerrorcode "refresh partition info"
 
 }
 
@@ -132,7 +150,7 @@ cleanuplog(){
 	if [ -e "/tmp/formatusb.log" ]; then
 		cp /tmp/formatusb.log /var/log/formatusb.log
 	fi
-	
+		
 }
 
 partnumber()
@@ -158,44 +176,48 @@ fi
 
 format_partitions(){
 	
-	echo "formatting partitions $device$partnum"
+	echo "formatting partitions $device$partnum"  
 		
 	#ensure device is unmounted
 	unmount_partitions
 
 	case $format in 
 
-	vfat) mkfs.fat -F 32 /dev/"$device$partnum" ;;
+	vfat) mkfs.fat -F 32 /dev/"$device$partnum"  ;;
 	
-	ext4)  mkfs.ext4 -F /dev/"$device$partnum"
+	ext4)  mkfs.ext4 -F /dev/"$device$partnum"  
 		   change_ownership;;
 	
-	ntfs)  mkfs.ntfs -Q /dev/"$device$partnum" ;;
+	ntfs)  mkfs.ntfs -Q /dev/"$device$partnum"  ;;
 	
 	exfat) mkfs.exfat /dev/"$device$partnum" ;;
 	
 	*)	echo "unknown format, exiting" ;;
+	
 
 
 esac
-	
+
+checkerrorcode "format partition"
 	
 }
 
 disable_automount()
 {
-mkdir -p /run/udev/rules.d
+mkdir -p /run/udev/rules.d  
+checkerrorcode "hide disk from udev"
 echo 'SUBSYSTEM=="block", ENV{UDISKS_IGNORE}="1"' > /run/udev/rules.d/91-mx-udisks-inhibit.rules
-udevadm control --reload
-udevadm trigger --subsystem-match=block
+udevadm control --reload  
+udevadm trigger --subsystem-match=block  
 
 }
 
 enable_automount()
 {
-rm -f /run/udev/rules.d/91-mx-udisks-inhibit.rules
-udevadm control --reload
-udevadm trigger --subsystem-match=block
+rm -f /run/udev/rules.d/91-mx-udisks-inhibit.rules  
+checkerrorcode "make disk visible to udev"
+udevadm control --reload   
+udevadm trigger --subsystem-match=block  
 }
 
 change_ownership()
@@ -204,13 +226,26 @@ change_ownership()
 	local GROUP=$(getent group users |awk -F: '{print $3}')
 	local USERNAME=$(/usr/bin/logname)
 	
-	mkdir -p /tmp/formatmountpoint
-	mount -t ext4 /dev/"$device$partnum" /tmp/formatmountpoint
-	echo "Changing owner of partition to $USERNAME:users"
+	mkdir -p /tmp/formatmountpoint 
+	mount -t ext4 /dev/"$device$partnum" /tmp/formatmountpoint    
 	chown $USERNAME:users /tmp/formatmountpoint
-	chmod 775 -R /tmp/formatmountpoint
-	umount -q /tmp/formatmountpoint
-	rmdir /tmp/formatmountpoint
+	checkerrorcode "Changing owner of partition to $USERNAME:users" 
+	chmod 775 -R /tmp/formatmountpoint  
+	checkerrorcode "Changing permissions of partition to $USERNAME:users"
+	umount -q /tmp/formatmountpoint  
+	rmdir /tmp/formatmountpoint  
+}
+
+checkerrorcode()
+{
+	local msg="$1"
+	#echo "exit code is $?"
+	if [ "$?" != "0" ]; then
+		echo "$msg" "ERRROR"
+		exit "$?"
+	else
+		echo "$msg" "OK"
+	fi
 }
 
 main(){
